#!/bin/bash
set -e

source "${SRCROOT}/Scripts/secrets-utils.sh"
GIT_SHA=$(get_git_commit_sha "${SRCROOT}")

# Generate BuildInfo.swift for the NotificationService extension
if [ "$TARGET_NAME" = "NotificationService" ]; then
    mkdir -p "${SRCROOT}/NotificationService"
    BUILD_INFO_PATH="${SRCROOT}/NotificationService/BuildInfo.swift"
    BUILD_INFO_CONTENT="// swiftlint:disable all
//
// This file is regenerated by Scripts/build-phases/copy-env-config-main-app.sh
// on every build. The committed placeholder exists only so the
// NotificationService target's file-synchronized group registers
// BuildInfo at Xcode planning time on a fresh CI checkout. Do not
// edit by hand — your changes will be overwritten on next build.
//
enum BuildInfo {
    static let commitHash: String = \"$(swift_escape "$GIT_SHA")\"
}
// swiftlint:enable all"
    if [ ! -f "$BUILD_INFO_PATH" ] || [ "$(cat "$BUILD_INFO_PATH")" != "$BUILD_INFO_CONTENT" ]; then
        printf '%s\n' "$BUILD_INFO_CONTENT" > "$BUILD_INFO_PATH"
        echo "🏁 Generated BuildInfo.swift for NotificationService (commit: $GIT_SHA)"
    else
        echo "✅ BuildInfo.swift already up-to-date (commit: $GIT_SHA)"
    fi
fi

# Part 1: Generate Secrets.swift for Local and Dev builds (App target only)
if [ "$TARGET_NAME" = "Convos" ] && [ "$CONFIGURATION" = "Local" ]; then
    echo "🏠 Local build detected - generating secrets for localhost"

    SECRETS_FILE="${SRCROOT}/Convos/Config/Secrets.swift"

    # Default to localhost for simulator builds. Use generate-secrets-local.sh --device
    # for physical device testing (which needs the LAN IP).
    LOCAL_IP="localhost"
    
    # Create directory if needed
    mkdir -p "${SRCROOT}/Convos/Config"
    
    # Start generating Secrets.swift
    cat > "$SECRETS_FILE" << 'HEADER_EOF'
import Foundation

// WARNING:
// This code is generated by the build phase for Local development.
// Do not edit this file directly. Your changes will be lost on next build.
// Git does not track this file.
// For Local builds, localhost is used by default (works with iOS Simulator).
// For physical device testing, run: ./Scripts/generate-secrets-local.sh --device

// swiftlint:disable all

/// Secrets are generated automatically for Local development
enum Secrets {
HEADER_EOF

    # Check if .env has custom values first, otherwise auto-detect
    CONVOS_API_BASE_URL=""
    XMTP_CUSTOM_HOST=""
    
    if [ -f "${SRCROOT}/.env" ]; then
        # Check for uncommented values in .env
        CONVOS_API_BASE_URL=$(grep -v '^#' "${SRCROOT}/.env" | grep '^CONVOS_API_BASE_URL=' | cut -d'=' -f2- | sed -e 's/^"//' -e 's/"$//' || true)
        XMTP_CUSTOM_HOST=$(grep -v '^#' "${SRCROOT}/.env" | grep '^XMTP_CUSTOM_HOST=' | cut -d'=' -f2- | sed -e 's/^"//' -e 's/"$//' || true)
    fi

    # Use .env values if present, otherwise auto-detect
    if [ -n "$CONVOS_API_BASE_URL" ]; then
        echo "🔧 Using CONVOS_API_BASE_URL from .env"
        echo "    static let CONVOS_API_BASE_URL = \"$CONVOS_API_BASE_URL\"" >> "$SECRETS_FILE"
    else
        echo "🔍 Using localhost for CONVOS_API_BASE_URL"
        echo "    static let CONVOS_API_BASE_URL = \"http://$LOCAL_IP:4000/api\"" >> "$SECRETS_FILE"
    fi

    if [ -n "$XMTP_CUSTOM_HOST" ]; then
        echo "🔧 Using XMTP_CUSTOM_HOST from .env"
        echo "    static let XMTP_CUSTOM_HOST = \"$XMTP_CUSTOM_HOST\"" >> "$SECRETS_FILE"
    else
        echo "🔍 Using localhost for XMTP_CUSTOM_HOST"
        echo "    static let XMTP_CUSTOM_HOST = \"$LOCAL_IP\"" >> "$SECRETS_FILE"
    fi

    echo "    static let GIT_COMMIT_SHA: String = \"$(swift_escape "$GIT_SHA")\"" >> "$SECRETS_FILE"

    # Add other secrets from .env if available
    if [ -f "${SRCROOT}/.env" ]; then
        echo "📋 Adding additional secrets from .env file..."

        # Process .env file: skip comments, empty lines, and IP-related keys (since we handled them above), then format as Swift
        sed -n '/^[^#]/p' "${SRCROOT}/.env" | grep '=' | grep -v '^CONVOS_API_BASE_URL' | grep -v '^XMTP_CUSTOM_HOST' | grep -v '^GIT_COMMIT_SHA' | sed 's/^\\([^=]*\\)=\\(.*\\)$/    static let \\1 = "\\2"/' | sed 's/""\\(.*\\)""/"\\1"/' >> "$SECRETS_FILE"
    fi
    
    # Close the enum
    cat >> "$SECRETS_FILE" << 'FOOTER_EOF'
}

// swiftlint:enable all
FOOTER_EOF
    
    echo "🏁 Generated Secrets.swift with localhost"

# Part 1b: Generate Secrets.swift for Dev builds
elif [ "$TARGET_NAME" = "Convos" ] && [ "$CONFIGURATION" = "Dev" ]; then
    echo "🔧 Dev build detected - generating secrets from .env"

    SECRETS_FILE="${SRCROOT}/Convos/Config/Secrets.swift"

    # Create directory if needed
    mkdir -p "${SRCROOT}/Convos/Config"

    CONVOS_API_BASE_URL=""
    if [ -f "${SRCROOT}/.env" ]; then
        CONVOS_API_BASE_URL=$(grep -v '^#' "${SRCROOT}/.env" | grep '^CONVOS_API_BASE_URL=' | cut -d'=' -f2- | sed -e 's/^"//' -e 's/"$//' || true)
    fi

    # Generate Secrets.swift for Dev
    cat > "$SECRETS_FILE" << EOF
import Foundation

// WARNING:
// This code is generated by the build phase for Dev development.
// Do not edit this file directly. Your changes will be lost on next build.
// Git does not track this file.

// swiftlint:disable all

/// Secrets are generated automatically for Dev development
enum Secrets {
    static let CONVOS_API_BASE_URL = "$CONVOS_API_BASE_URL"
    static let XMTP_CUSTOM_HOST = ""
    static let GATEWAY_URL = ""
    static let SENTRY_DSN = ""
    static let GIT_COMMIT_SHA: String = "$(swift_escape "$GIT_SHA")"
}

// swiftlint:enable all
EOF

    echo "🏁 Generated Secrets.swift for Dev"
fi

# Part 2: Copy config file (existing functionality)
CONFIG_SOURCE="${SRCROOT}/Convos/Config/${CONFIG_FILE}"
CONFIG_DEST="${TARGET_BUILD_DIR}/${WRAPPER_NAME}/config.json"

if [ ! -f "$CONFIG_SOURCE" ]; then
    echo "error: Config file not found: $CONFIG_SOURCE (CONFIG_FILE=$CONFIG_FILE)"
    exit 1
fi

echo "📋 Copying $CONFIG_FILE to app bundle"
cp "$CONFIG_SOURCE" "$CONFIG_DEST"
echo "✅ Config copied successfully"
