import 'dotenv/config';
import { z } from 'zod';

const schema = z.object({
  NODE_ENV: z.enum(['development', 'production', 'test']).default('development'),

  PORT: z.coerce.number().int().default(4000),
  HOST: z.string().default('0.0.0.0'),
  LOG_LEVEL: z.enum(['fatal', 'error', 'warn', 'info', 'debug', 'trace']).default('info'),

  // Public origin the iOS app uses to reach this API. With the Cloudflare
  // quick tunnel this is the ephemeral trycloudflare.com hostname; with a
  // named tunnel it's a custom domain. Used to build attachment URLs.
  // An empty value in .env is treated as unset and falls back to
  // http://<host>:<port>.
  PUBLIC_BASE_URL: z.preprocess(
    (v) => (v === '' ? undefined : v),
    z.string().url().optional(),
  ),

  DATABASE_URL: z.string().min(1, 'DATABASE_URL is required'),

  JWT_SECRET: z.string().min(32, 'JWT_SECRET must be at least 32 chars (use: openssl rand -hex 32)'),
  // Access-token TTL. Short by design — refresh tokens (30-day default)
  // cover continuity. See src/auth/refresh-tokens.ts and security plan
  // item 11.
  JWT_TTL_SECONDS: z.coerce.number().int().positive().default(3600),
  // Refresh-token TTL. 30 days matches the default mobile-OS app-resume
  // window before the user re-logins. Lower it (e.g. 7) for high-risk
  // deployments; raise it (e.g. 90) if you accept the longer theft
  // window in exchange for fewer re-auths.
  REFRESH_TTL_DAYS: z.coerce.number().int().positive().default(30),

  // `local` writes attachment bytes to LOCAL_STORAGE_DIR on the backend
  // host and serves them via /v2/_local-asset/... — the path the iOS
  // client expects for working RemoteAttachments. `mock` is kept for
  // backwards compatibility but discards bytes and returns dead URLs,
  // which silently breaks PDF / image / attachment delivery. Never the
  // default. `lighthouse` is the IPFS option.
  STORAGE_PROVIDER: z.enum(['lighthouse', 'mock', 'local']).default('local'),
  LIGHTHOUSE_API_KEY: z.string().optional(),
  LIGHTHOUSE_WALLET_PRIVATE_KEY: z.string().optional(),
  IPFS_GATEWAY: z.string().url().default('https://gateway.lighthouse.storage/ipfs'),

  // Directory the 'local' storage provider writes attachment bytes to. In
  // Docker this is a mounted volume; locally it defaults under the CWD.
  LOCAL_STORAGE_DIR: z.string().default('./.attachments'),

  // Directory the reports-agent watches for finished PDF reports the
  // operator wants to ship to clients. Files dropped into this directory
  // are picked up automatically; see src/agent/reports-watcher.ts.
  REPORTS_DIR: z.string().default('./reports'),

  CORS_ORIGIN: z.string().default('*'),

  // SIWE auth — domain + URI baked into challenge messages so signatures
  // can't be replayed against a different deployment.
  SIWE_DOMAIN: z.string().default('local.goldilocksdigital.xyz'),
  SIWE_URI: z.string().url().default('http://localhost:4000/api/v2/me'),

  // XMTP node gRPC — used to verify a caller's eth address is bound to
  // the inbox they claim. Defaults match `dev/up`.
  XMTP_GRPC_URL: z.string().default('localhost:5556'),
  XMTP_GRPC_SECURE: z.coerce.boolean().default(false),

  // XMTP network the server-side agents (admins-agent, reports-agent)
  // connect to. Must match the network the iOS app is on. 'local' points
  // at the convos-ios `./dev/up` node.
  XMTP_NETWORK: z.enum(['local', 'dev', 'production']).default('local'),
  // Custom XMTP API URL for 'local' network. Ignored on dev/production.
  // The convos-ios local node serves gRPC on 5556 (h2c) — the iOS client
  // hits the same port.
  XMTP_API_URL: z.string().default('http://localhost:5556'),

  // Where each agent stores its local SQLCipher DB. One file per agent
  // (admins.db3, reports.db3). Defaults to ./.agent-data relative to the
  // CWD so local dev works without editing .env. Override to an absolute
  // path (e.g. /var/lib/goldilocks-agent inside docker) for prod.
  AGENT_DB_DIR: z.string().default('./.agent-data'),

  // 32-byte hex (without 0x prefix is fine) used to encrypt the agent's
  // local XMTP DB. Generate with: openssl rand -hex 32
  AGENT_DB_ENCRYPTION_KEY: z.string().default(''),

  // F4 — App-layer encryption for sensitive DB columns (server_agents
  // private keys, admin upgrade codes, Stripe identifiers, push tokens).
  // Generated by the CLI's Settings → Run setup. 64 hex chars. Optional
  // here so existing installs don't fail to start; the at-rest codec
  // surfaces a clear error if ENCRYPT_AT_REST_V1 is on without it.
  APP_ENCRYPTION_KEY: z.preprocess(
    (v) => (v === '' ? undefined : v),
    z.string().regex(/^[0-9a-fA-F]{64}$/, 'APP_ENCRYPTION_KEY must be 64 hex chars').optional(),
  ),

  // Master switch for column encryption writes. Reads are always tolerant
  // of both formats so the rollout can be gradual. New installs default
  // to true (the CLI's setup sets it explicitly); existing installs stay
  // at false until the operator flips it after running the column-
  // migration script. See docs/encryption-and-backup-plan.md F4.
  ENCRYPT_AT_REST_V1: z.coerce.boolean().default(false),

  // DEV-ONLY: when true, /v2/admin/promote-self is enabled. NEVER set this
  // in production — anyone with a JWT could grant themselves admin.
  GOLDILOCKS_ALLOW_SELF_PROMOTE: z.coerce.boolean().default(false),

  // Stripe billing. All optional so the server still boots without them;
  // the /v2/billing/* routes return 503 until a secret key is configured.
  //   STRIPE_SECRET_KEY     — sk_test_… in dev, sk_live_… in production.
  //   STRIPE_WEBHOOK_SECRET — whsec_… signing secret for /v2/stripe/webhook.
  //                           In local dev this comes from `stripe listen`.
  //   STRIPE_SUCCESS_URL /  — where Stripe redirects the browser after a
  //   STRIPE_CANCEL_URL       checkout. Left blank, they default to the
  //                           backend's own /v2/billing/return + /cancel
  //                           landing pages derived from PUBLIC_BASE_URL.
  STRIPE_SECRET_KEY: z.preprocess((v) => (v === '' ? undefined : v), z.string().optional()),
  STRIPE_WEBHOOK_SECRET: z.preprocess((v) => (v === '' ? undefined : v), z.string().optional()),
  STRIPE_SUCCESS_URL: z.preprocess((v) => (v === '' ? undefined : v), z.string().url().optional()),
  STRIPE_CANCEL_URL: z.preprocess((v) => (v === '' ? undefined : v), z.string().url().optional()),
});

const parsed = schema.safeParse(process.env);
if (!parsed.success) {
  console.error('Invalid environment configuration:');
  console.error(parsed.error.flatten().fieldErrors);
  process.exit(1);
}

export const config = parsed.data;
export type Config = typeof config;
