import Fastify from 'fastify';
import cors from '@fastify/cors';
import helmet from '@fastify/helmet';
import rateLimit from '@fastify/rate-limit';
import sensible from '@fastify/sensible';
import { config } from './config.js';
import { pool } from './db/client.js';
import authRoutes from './routes/auth.js';
import deviceRoutes from './routes/devices.js';
import notificationRoutes from './routes/notifications.js';
import attachmentRoutes from './routes/attachments.js';
import healthRoutes from './routes/health.js';
import meRoutes from './routes/me.js';
import channelRoutes from './routes/channels.js';
import billingRoutes from './routes/billing.js';
import stripeWebhookRoutes from './routes/stripe-webhook.js';

async function build() {
  const app = Fastify({
    // Behind the Cloudflare tunnel, so trust X-Forwarded-* headers to
    // recover the real client IP — rate limiting keys on it.
    trustProxy: true,
    logger: {
      level: config.LOG_LEVEL,
      transport:
        config.NODE_ENV === 'production'
          ? undefined
          : { target: 'pino-pretty', options: { colorize: true, translateTime: 'HH:MM:ss.l' } },
    },
    bodyLimit: 50 * 1024 * 1024, // 50MB for attachment proxy uploads
  });

  // Close the Postgres pool when Fastify shuts down.
  app.addHook('onClose', async () => {
    await pool.end();
  });

  await app.register(sensible);
  await app.register(helmet);
  // Global per-IP rate limit. Generous for normal app traffic, low enough
  // that brute-forcing the 16-digit admin upgrade code is hopeless.
  await app.register(rateLimit, {
    max: 120,
    timeWindow: '1 minute',
  });
  await app.register(cors, {
    origin: config.CORS_ORIGIN === '*' ? true : config.CORS_ORIGIN.split(',').map((s) => s.trim()),
    credentials: true,
  });

  // Accept raw bytes on the lighthouse upload route so we can forward bodies.
  app.addContentTypeParser('*', { parseAs: 'buffer' }, (_req, body, done) => {
    done(null, body);
  });

  const publicBaseUrl =
    config.PUBLIC_BASE_URL ??
    `http://${config.HOST === '0.0.0.0' ? 'localhost' : config.HOST}:${config.PORT}`;

  // The iOS client builds URLs by appending paths to apiBaseURL, which is
  // generated by Scripts/generate-secrets-local.sh as `http://<lan>:4000/api`.
  // So everything we expose lives under /api.
  await app.register(healthRoutes);

  // Convos's iOS app fetches this on launch to verify agent signatures.
  // Goldilocks doesn't have agents, so return an empty key list.
  app.get('/.well-known/agents.json', async () => ({ keys: [] }));

  await app.register(
    async (api) => {
      await api.register(authRoutes);
      await api.register(deviceRoutes);
      await api.register(meRoutes);
      await api.register(channelRoutes);
      await api.register(notificationRoutes);
      await api.register(attachmentRoutes, { publicBaseUrl });
      await api.register(billingRoutes, { publicBaseUrl });
      // Registered as its own plugin so its raw-body parser (needed for
      // Stripe signature verification) stays encapsulated.
      await api.register(stripeWebhookRoutes);

      // Convos-compatible stubs we explicitly don't implement.
      // Returning 410 Gone makes failures explicit rather than mysteriously hanging.
      for (const path of [
        '/v2/invite-codes/redeem',
        '/v2/invite-codes/:code/status',
        '/v2/agents/join',
        '/v2/connections/initiate',
        '/v2/connections/complete',
        '/v2/connections',
        '/v2/connections/:connectionId',
      ]) {
        api.all(path, async (_req, reply) => {
          return reply.code(410).send({
            error: 'not_implemented_in_goldilocks',
            message: 'This endpoint is part of Convos but not supported in Goldilocks.',
          });
        });
      }
    },
    { prefix: '/api' },
  );

  return app;
}

build()
  .then(async (app) => {
    const shutdown = async (signal: string): Promise<void> => {
      app.log.info(`received ${signal}, shutting down`);
      try {
        await app.close();
      } catch (err) {
        app.log.error(err);
      }
      process.exit(0);
    };
    process.on('SIGTERM', () => void shutdown('SIGTERM'));
    process.on('SIGINT', () => void shutdown('SIGINT'));

    try {
      await app.listen({ port: config.PORT, host: config.HOST });
    } catch (err) {
      app.log.error(err);
      process.exit(1);
    }
  })
  .catch((err) => {
    console.error('Failed to build server:', err);
    process.exit(1);
  });
