default_platform(:ios)

# Reusable constants
PROJECT          = "Convos.xcodeproj"

# PR (ad-hoc, Firebase) flavor
PR_SCHEME        = "Convos (PR Preview)"
PR_CONFIG        = "PR Preview"
PR_BUNDLE_ID     = "org.convos.ios-preview.pr"
PR_NSE_BUNDLE_ID = "org.convos.ios-preview.pr.ConvosNSE"

# Dev (App Store, TestFlight) flavor
DEV_SCHEME           = "Convos (Dev)"
DEV_CONFIG           = "Dev"
DEV_BUNDLE_ID        = "org.convos.ios-preview"
DEV_NSE_BUNDLE_ID    = "org.convos.ios-preview.ConvosNSE"
DEV_CLIP_BUNDLE_ID   = "org.convos.ios-preview.Clip"

MATCH_GIT_URL    = ENV["MATCH_GIT_URL"] || "git@github.com:xmtplabs/convos-certificates.git"
OUTPUT_DIR       = "build"
OUTPUT_NAME      = "Convos-PR.ipa"


import "lanes/match.rb"
import "lanes/firebase.rb"
import "lanes/release.rb"
import "lanes/helpers.rb"
import "lanes/bootstrap.rb"
